name: JellyBaMM
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - plotly
  - openpyxl
  - tqdm
  - networkx
  - jupyter
  - sympy
  - ipython
  - wrapt
  - sympy
  - redis
  - pyyaml
  - protobuf >=3.8.0,<4.0.0
  - imageio
  - grpcio
  - future
  - flatbuffers
  - filelock
  - deprecated
  - click
  - autograd
  - absl-py
  - dask
  - hiredis
  - ipywidgets
  - pip:
    - pybamm==23.9
    - liionpack==0.3.8
    - openpnm==2.8.2
    - mkdocstrings-python-legacy
    - mkdocs-material
    - mkdocs-jupyter