name: JellyBaMM CI

on:
  pull_request:
  push:
    branches: ["main"]
  schedule:
    - cron:  '0 3 * * *'

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run tests and collect coverage
        run: pytest --cov=jellybamm --cov-report=xml
      - name: Upload coverage to Codecov
      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true # optional (default = false)
          name: codecov-umbrella # optional
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)
      - name: Build docs
        run: |
          mkdocs build
